### ISSUE TITLE
Widget error

### ISSUE THREAD

**Issue by mjanez** [OpenDataGIS/ckanext-iepnb#2]
**Descripción**
Al tratar de dibujar la extensión del filtrado por localización se descuadra el mapa del popup.

**Reproducción**
Pasos para reproducir el comportamiento:
1. En la sección de metadatos del portal ir a 'Filter by location'
2. Haga clic en 'Draw an extent'
3. Ver error

**Comportamiento esperado**
La caja de extensión debería integrarse correctamente en el elemento `modal-content`.

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/96422458/232481708-da08a65a-cdc2-49bc-8a14-69f1ec0d4745.png)

**Escritorio (por favor, complete la siguiente información):**
 - Navegador Firefox
 - Versión 111.0 (64-bit)

**Contexto adicional**
Si pudiera ser útil, hay información sobre la actualización de librerías y la integración con Bootstrap 5 de ckanext-spatial: https://github.com/ckan/ckanext-spatial/pull/304

**Comment by dsanjurjo** [comment]
Solucionado en versión 7ba8e05
