### ISSUE TITLE
Bug - dropdown-toggle bugs

### ISSUE THREAD

**Issue by mjanez** [OpenDataGIS/ckanext-iepnb#36]
Duplication of `caret` elements in `ckanext-iepnb` dropdown-toggle.

https://des.iepnb.es/catalogo/dataset/fe757d64-436c-482d-b65b-f24348139fd6
![image](https://github.com/OpenDataGIS/ckanext-iepnb/assets/96422458/3be4ee08-28df-4bec-8ff0-d110eac8fd74)
![image](https://github.com/OpenDataGIS/ckanext-iepnb/assets/96422458/38fe5c08-af39-444a-bd36-6591820ce599)

Fix, a normal download button should appear:
See works on: https://hermes.tragsatec.es/catalogo/dataset/f2a5678e-ee8f-4ab6-892c-5fc10fb26339
![image](https://github.com/OpenDataGIS/ckanext-iepnb/assets/96422458/40e22c90-3a59-4875-a347-c351b5b56e17)

**Comment by dsanjurjo** [comment]
Entiendo que en vez de un botón para cada recurso de metadatos, se quiere un desplegable único para metadatos en el que se pueda seleccionar el formato de estos. Queda ver como integrarlo con el resto de recursos del dataset, ya que los metadatos son solo uno de los tipos de recursos que puede haber en un dataset.
![tmp](https://github.com/OpenDataGIS/ckanext-iepnb/assets/118907663/2ad76c32-20f3-47f2-ba53-0d44744eea0a)

**Comment by mjanez** [comment]
No, no tiene nada que ver con eso.

Es un error estético en el que aparecen dos `carets` (flechas hacia abajo) en el boton CSS, en ckanext-iepnb.

**Comment by dsanjurjo** [comment]
solución actualizada en rama develop
