### ISSUE TITLE
Missing harvest icon

### ISSUE THREAD

**Issue by mjanez** [OpenDataGIS/ckanext-iepnb#6]
Missing icon causes a failed image in the template.

https://github.com/OpenDataGIS/ckanext-iepnb/blob/19d216eadce55ef89c83697228f06def93156507/ckanext/iepnb/templates/home/columna_izquierda.html#L22-L25

### Solution
- [ ] Create an icon and add to [`ckanext-iepnb/tree/main/ckanext/iepnb/public/img`](https://github.com/OpenDataGIS/ckanext-iepnb/tree/main/ckanext/iepnb/public/img)

**Comment by dsanjurjo** [comment]
Cerrado con la versión #18aa00b
