### ISSUE TITLE
Contenido Actualidad/Ayuda

### ISSUE THREAD

**Issue by mjanez** [OpenDataGIS/ckanext-iepnb#8]
https://des.iepnb.es/
![image](https://user-images.githubusercontent.com/96422458/233587609-598b1ab0-2394-4bae-94ac-c2fc5ab52877.png)

https://des.iepnb.es/catalogo
![image](https://user-images.githubusercontent.com/96422458/233587514-1e00d87c-3d6b-4065-b6d9-5a54a2954e96.png)

### Error
En Drupal, si dejas el ratón sobre "Actualidad" o "Ayuda" no despliega nada porque no hay nada debajo. Pero 
en CKAN, crea un bloque con borde visible, aunque sin contenido.

### Solución
Eliminar la creación del bloque al pasar el ratón.

**Comment by dsanjurjo** [comment]
Solucionado en la versión 18aa00b
